name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

# Permissions required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Sync web/version.json from pubspec
        run: dart run tool/sync_version.dart

      - name: Analyze Flutter code
        run: flutter analyze --no-fatal-infos

      - name: Run Flutter tests
        run: flutter test

      - name: Build Flutter web
        run: flutter build web --release --base-href "/mti_pontianak/"

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4